load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "winmd_reader",
    srcs = [
        "winmd_reader.h",
    ],
    deps = [
        "//src/impl:winmd_reader_impl"
    ]
)
