package(default_visibility = ["//visibility:public"])

load(":midl_test.bzl", "midl_test_suite")

midl_test_suite(name="midl_test_suite")

load(":cppwinrt_test.bzl", "cppwinrt_test_suite")

cppwinrt_test_suite(name="cppwinrt_test_suite")