workspace(name = "com_github_sammi_tuware_b2m_midl")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_skylib",
    sha256 = "cea47b31962206b7ebf2088f749243868d5d9305273205bdd8651567d3e027fc",
    strip_prefix = "bazel-skylib-b113ed5d05ccddee3093bb157b9b02ab963c1c32",
    url = "https://github.com/bazelbuild/bazel-skylib/archive/b113ed5d05ccddee3093bb157b9b02ab963c1c32.zip",
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

load("//compiler:deps.bzl", "midl_bat_repo", "cppwinrt_bat_repo")

#Build midl.bat as the code generator, which could generate c++ header source code and winmd binary meta file.
midl_bat_repo(name = "midl")

#Build cppwinrt.bat as the code generator, which could generate c++ header source code from winmd binary meta file.
cppwinrt_bat_repo(name="cppwinrt")
