load("//build:midl.bzl", "midl")
load("//build:midl_test.bzl", "midl_test_suite")

package(default_visibility = ["//visibility:public"])

midl(
    name = "CloudBuilder",
    idl = "CloudBuilder.idl",
)


midl_test_suite(name="midl_test")