load("//bazel:midl.bzl", "midl")
load("//bazel:cppwinrt.bzl", "cppwinrt")

package(default_visibility = ["//visibility:public"])

midl(
    name = "CloudBuilder",
    idl = "CloudBuilder.idl",
)


# cppwinrt(
#     name = "winrt/CloudBuilder",
#     winmd = "CloudBuilder.winmd"
# )