load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "winmd_reader_impl",
    srcs = [
        "base.h",
    ],
    deps = [
        "//src/impl/winmd_reader:winmd_reader_lib",
    ],
)
