name: Publish package to GitHub Packages

on:
    push:
        branches:
            - release
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v1
              with:
                  java-version: 1.8
            - name: actions-setup-bazel
              uses: jwlawson/actions-setup-bazel@v1.6
              with:
                  bazel-version: '4.0.0'
            - name: Use bazel
              run: bazel --version
            - name: Configure Git user
              run: |
                git config user.email "actions@github.com"
                git config user.name "GitHub Actions"

            - name: get release version
              run: echo ::set-output name=release_version::$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
              id: project

            - name: Prepare Release
              run: mvn -B release:prepare

            - name: Publish JAR
              run: mvn -B release:perform
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Get Previous tag
              id: previoustag
              uses: "WyriHaximus/github-action-get-previous-tag@v1"

            - name: Remove letter v from tag
              run: echo ::set-output name=version::$( echo ${{steps.previoustag.outputs.tag}} | cut -c2-)
              id: tagVersion

            - name: package cli module jar file
              run: mvn clean install && cd cli && mvn package && mkdir release && mv target/cli-*.jar release/cli.jar && mv target/libs release/. && mv b2m* release/.

            - name: Zip release files
              uses: vimtor/action-zip@v1
              with:
                files: cli/release
                recursive: true
                dest: b2m-${{steps.tagVersion.outputs.version}}.zip

            - name: Pre release
              uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "${{steps.previoustag.outputs.tag}}"
                  prerelease: true
                  title: "bazel to msbuild converter for cpp console app"
                  files: |
                      b2m-${{steps.tagVersion.outputs.version}}.zip
