name: Publish package to GitHub Packages

on:
    push:
        branches:
            - release
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v1
              with:
                  java-version: 1.8
            - name: Configure Git user
              run: |
                git config user.email "actions@github.com"
                git config user.name "GitHub Actions"
            - name: Prepare Release
              run: mvn --batch-mode release:prepare
            - name: Publish package
              run: mvn --batch-mode release:perform
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
